[build]
  command = "next build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "@netlify/plugin-functions"

[build.environment]
  WAKEUP_FUNCTION_PATH = "netlify/functions/wakeup.js"

[[plugins.inputs]]
  schedule = "*/10 * * * *"
  command = "curl $WAKEUP_FUNCTION_PATH"